version: '3'

services:
  env_ore_1:
    image: env_ore_1:${ORE_TAG}
    cap_drop:
      - NET_RAW
    build:
      context: ../
      dockerfile: Docker/Dockerfile-ORE-1
      args:
        - debian_tag=${DEBIAN_TAG}
        - cmake_build_type=${CMAKE_BUILD_TYPE}
        - num_cores=${NUM_CORES}
