version: '3'

volumes:
    ccache_volume:

services:
  env_ore:
    image: env_ore:${ORE_TAG}
    environment:
      - CCACHE_DIR=/ccache
    build:
      context: ../
      dockerfile: Docker/Dockerfile-ORE
      volumes:
        - ccache_volume:ccache
      args:
        - quantlib_version=${QL_TAG}
        - num_cores=${NUM_CORES}
