version: '3'

services:
  env_ore:
    image: env_ore
    build:
      context: ../
      dockerfile: Docker/Dockerfile-ORE
      args:
        - quantlib_version=1.18_7601dc978
        - num_cores=16
