version: '3'

services:
  env_ore_debug:
    image: env_ore_debug
    build:
      context: ../
      dockerfile: Docker/Dockerfile-ORE-Debug
      args:
        - quantlib_version=1.18_85f5422d9
        - num_cores=16
