version: '3'

services:
  env_ore:
    image: env_ore:${ORE_TAG}
    environment:
      - CCACHE_DIR=/ccache
    build:
      context: ../
      dockerfile: Docker/Dockerfile-ORE
      volumes_from:
        - cachev
      args:
        - quantlib_version=${QL_TAG}
        - num_cores=${NUM_CORES}
