version: '3'

services:
  env_ore:
    image: env_ore
    build:
      context: ../
      dockerfile: Docker/Dockerfile-ORE
      args:
        - quantlib_version=1.18_ac6b843f8
        - num_cores=16
